-- INSERIR DADOS NA TABELA BASE_USER PARA A GERENCIA
INSERT INTO BASE_USER (UID, NOME, EMAIL, NIVEL)
VALUES
  ('c7PtkoKRVpfUWcRVPgigIy3IV262', 'Nome da Gerência', 'email@example.com', 0);

-- INSERIR DADOS NA TABELA GERENCIA
INSERT INTO GERENCIA (ID, NOME_ACADEMIA, CNPJ, SENHA)
VALUES
  (1, 'Nome da Academia', '12345678901234', 'senha123');



-- INSERIR DADOS NA TABELA BASE_USER PARA OS INSTRUTORES
INSERT INTO BASE_USER (UID, NOME, EMAIL, NIVEL)
VALUES
  ('uid_instrutor_1', 'João Silva', 'joao.silva@example.com', 1),
  ('uid_instrutor_2', 'Maria Oliveira', 'maria.oliveira@example.com', 1),
  ('uid_instrutor_3', 'Carlos Santos', 'carlos.santos@example.com', 1);

-- INSERIR DADOS NA TABELA INSTRUTOR
INSERT INTO INSTRUTOR (ID, HORARIO, SENHA_TEMPORARIA)
VALUES
  (2, '09:00-11:00', 'senha123'),
  (3, '14:00-16:00', 'senha456'),
  (4, '11:00-13:00', 'senha789');


-- INSERIR NA TABELA DE RELAÇÕES GERENCIA COM INSTRUTORES
INSERT INTO GERENCIA_INSTRUTORES (GERENCIA_ID, INSTRUTORES_ID) VALUES(1,2);
INSERT INTO GERENCIA_INSTRUTORES (GERENCIA_ID, INSTRUTORES_ID) VALUES(1,3);
INSERT INTO GERENCIA_INSTRUTORES (GERENCIA_ID, INSTRUTORES_ID) VALUES(1,4);


-- INSERIR DADOS NA TABELA BASE_USER PARA O ALUNO
INSERT INTO BASE_USER (UID, NOME, EMAIL, NIVEL)
VALUES
  ('c7PtkoKRVpfUWcRVPgigIy3IV222', 'João Felix', 'aluno@example.com', 2);


-- INSERIR DADOS NA TABELA ALUNO
INSERT INTO ALUNO (ID) VALUES (5);