-- INSERIR DADOS NA TABELA GERENCIA
INSERT INTO GERENCIA (NOME, NOME_ACADEMIA, EMAIL, CNPJ, SENHA, UID)
VALUES ('Nome da Gerência', 'Nome da Academia', 'email@example.com', '12345678901234', 'senha123', 'c7PtkoKRVpfUWcRVPgigIy3IV262');

-- INSERIR DADOS NA TABELA INSTRUTOR
INSERT INTO INSTRUTOR (UID, NOME, EMAIL, DATA_NASCIMENTO, SEXO, HORARIO, SENHA_TEMPORARIA)
VALUES ('uid_instrutor_1', 'João Silva', 'joao.silva@example.com', '1980-03-15', 'Masculino', '09:00-11:00', 'senha123');

INSERT INTO INSTRUTOR (UID, NOME, EMAIL, DATA_NASCIMENTO, SEXO, HORARIO, SENHA_TEMPORARIA)
VALUES ('uid_instrutor_2', 'Maria Oliveira', 'maria.oliveira@example.com', '1992-07-20', 'Feminino', '14:00-16:00', 'senha456');

INSERT INTO INSTRUTOR (UID, NOME, EMAIL, DATA_NASCIMENTO, SEXO, HORARIO, SENHA_TEMPORARIA)
VALUES ('uid_instrutor_3', 'Carlos Santos', 'carlos.santos@example.com', '1985-12-10', 'Masculino', '11:00-13:00', 'senha789');

-- INSERIR NA TABELA DE RELAÇÕES GERENCIA COM INSTRUTORES
INSERT INTO GERENCIA_INSTRUTORS (GERENCIA_ID, INSTRUTORS_ID) VALUES(1,1);
INSERT INTO GERENCIA_INSTRUTORS (GERENCIA_ID, INSTRUTORS_ID) VALUES(1,2);
INSERT INTO GERENCIA_INSTRUTORS (GERENCIA_ID, INSTRUTORS_ID) VALUES(1,3);