-- INSERIR DADOS NA TABELA BASE_USER PARA OS INSTRUTORES
INSERT INTO BASE_USER (UID, NOME, EMAIL, NIVEL)
VALUES
  ('uid_instrutor_1', 'João Silva', 'joao.silva@example.com', 0),
  ('uid_instrutor_2', 'Maria Oliveira', 'maria.oliveira@example.com', 0),
  ('uid_instrutor_3', 'Carlos Santos', 'carlos.santos@example.com', 0);

-- INSERIR DADOS NA TABELA INSTRUTOR
INSERT INTO INSTRUTOR (ID, HORARIO, SENHA_TEMPORARIA)
VALUES
  (1, '09:00-11:00', 'senha123'),
  (2, '14:00-16:00', 'senha456'),
  (3, '11:00-13:00', 'senha789');

-- INSERIR DADOS NA TABELA BASE_USER PARA A GERENCIA
INSERT INTO BASE_USER (UID, NOME, EMAIL, NIVEL)
VALUES
  ('c7PtkoKRVpfUWcRVPgigIy3IV262', 'Nome da Gerência', 'email@example.com', 1);

-- INSERIR DADOS NA TABELA GERENCIA
INSERT INTO GERENCIA (ID, NOME_ACADEMIA, CNPJ, SENHA)
VALUES
  (4, 'Nome da Academia', '12345678901234', 'senha123');

-- INSERIR NA TABELA DE RELAÇÕES GERENCIA COM INSTRUTORES
INSERT INTO GERENCIA_INSTRUTORES (GERENCIA_ID, INSTRUTORES_ID) VALUES(4,1);
INSERT INTO GERENCIA_INSTRUTORES (GERENCIA_ID, INSTRUTORES_ID) VALUES(4,2);
INSERT INTO GERENCIA_INSTRUTORES (GERENCIA_ID, INSTRUTORES_ID) VALUES(4,3);